# Intent Monitoring Configuration Example - Wildcard Mode
# This configuration uses wildcard patterns to subscribe to topics

transport:
  enable_gossipsub: true
  gossipsub_heartbeat_interval: 1s
  gossipsub_d: 6
  gossipsub_d_lo: 4
  gossipsub_d_hi: 12
  gossipsub_fanout_ttl: 60s
  enable_message_signing: true
  enable_strict_signature_verification: true
  message_id_cache_size: 1000
  message_ttl: 300s
  max_message_size: 1048576

  # Intent monitoring configuration - Wildcard Mode
  intent_monitoring:
    # Use wildcard patterns to match topics
    subscription_mode: "wildcard"

    # Wildcard patterns for topic matching
    wildcard_patterns:
      - "intent-broadcast.*" # All intent broadcast topics
      - "intent-matching.*" # All intent matching topics
      - "intent-notification.*" # All intent notification topics

    # Intent filter configuration
    filter:
      # Only monitor specific intent types
      allowed_types:
        - "trade"
        - "swap"
        - "exchange"
      blocked_types: []
      allowed_senders: []
      blocked_senders: []
      min_priority: 1
      max_priority: 10

    # Statistics configuration
    statistics:
      enabled: true
      retention_period: "12h"
      aggregation_interval: "30s"

    # Performance configuration
    performance:
      max_subscriptions: 50
      message_buffer_size: 500
      batch_size: 5
