// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
	"pin_intent_broadcast_network/internal/biz"
	"pin_intent_broadcast_network/internal/biz/intent"
	"pin_intent_broadcast_network/internal/conf"
	"pin_intent_broadcast_network/internal/data"
	"pin_intent_broadcast_network/internal/p2p"
	"pin_intent_broadcast_network/internal/server"
	"pin_intent_broadcast_network/internal/service"
	"pin_intent_broadcast_network/internal/transport"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := bootstrap.Server
	confData := bootstrap.Data
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	intentService := service.NewIntentService(logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, intentService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, intentService, logger)
	zapLogger := NewZapLogger(logger)
	networkManager := p2p.NewNetworkManager(zapLogger)
	transportManager := transport.NewTransportManagerWithP2P(networkManager, zapLogger)
	config := intent.NewConfig()
	manager := intent.NewManagerWithDefaults(transportManager, config, logger)
	app := newApp(logger, grpcServer, httpServer, networkManager, transportManager, manager, bootstrap)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// NewZapLogger creates a zap logger from kratos logger
func NewZapLogger(logger log.Logger) *zap.Logger {

	zapLogger, _ := zap.NewProduction()
	return zapLogger
}
