// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	P2P           *P2P                   `protobuf:"bytes,3,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Transport     *Transport             `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetP2P() *P2P {
	if x != nil {
		return x.P2P
	}
	return nil
}

func (x *Bootstrap) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type P2P struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ListenAddresses []string               `protobuf:"bytes,1,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listen_addresses,omitempty"`
	BootstrapPeers  []string               `protobuf:"bytes,2,rep,name=bootstrap_peers,json=bootstrapPeers,proto3" json:"bootstrap_peers,omitempty"`
	ProtocolId      string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	EnableMdns      bool                   `protobuf:"varint,4,opt,name=enable_mdns,json=enableMdns,proto3" json:"enable_mdns,omitempty"`
	EnableDht       bool                   `protobuf:"varint,5,opt,name=enable_dht,json=enableDht,proto3" json:"enable_dht,omitempty"`
	DataDir         string                 `protobuf:"bytes,6,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	MaxConnections  int32                  `protobuf:"varint,7,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	EnableSigning   bool                   `protobuf:"varint,8,opt,name=enable_signing,json=enableSigning,proto3" json:"enable_signing,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *P2P) Reset() {
	*x = P2P{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2P) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2P) ProtoMessage() {}

func (x *P2P) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2P.ProtoReflect.Descriptor instead.
func (*P2P) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *P2P) GetListenAddresses() []string {
	if x != nil {
		return x.ListenAddresses
	}
	return nil
}

func (x *P2P) GetBootstrapPeers() []string {
	if x != nil {
		return x.BootstrapPeers
	}
	return nil
}

func (x *P2P) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *P2P) GetEnableMdns() bool {
	if x != nil {
		return x.EnableMdns
	}
	return false
}

func (x *P2P) GetEnableDht() bool {
	if x != nil {
		return x.EnableDht
	}
	return false
}

func (x *P2P) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *P2P) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *P2P) GetEnableSigning() bool {
	if x != nil {
		return x.EnableSigning
	}
	return false
}

type Transport struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	EnableGossipsub                   bool                   `protobuf:"varint,1,opt,name=enable_gossipsub,json=enableGossipsub,proto3" json:"enable_gossipsub,omitempty"`
	GossipsubHeartbeatInterval        *durationpb.Duration   `protobuf:"bytes,2,opt,name=gossipsub_heartbeat_interval,json=gossipsubHeartbeatInterval,proto3" json:"gossipsub_heartbeat_interval,omitempty"`
	GossipsubD                        int32                  `protobuf:"varint,3,opt,name=gossipsub_d,json=gossipsubD,proto3" json:"gossipsub_d,omitempty"`
	GossipsubDLo                      int32                  `protobuf:"varint,4,opt,name=gossipsub_d_lo,json=gossipsubDLo,proto3" json:"gossipsub_d_lo,omitempty"`
	GossipsubDHi                      int32                  `protobuf:"varint,5,opt,name=gossipsub_d_hi,json=gossipsubDHi,proto3" json:"gossipsub_d_hi,omitempty"`
	GossipsubFanoutTtl                *durationpb.Duration   `protobuf:"bytes,6,opt,name=gossipsub_fanout_ttl,json=gossipsubFanoutTtl,proto3" json:"gossipsub_fanout_ttl,omitempty"`
	EnableMessageSigning              bool                   `protobuf:"varint,7,opt,name=enable_message_signing,json=enableMessageSigning,proto3" json:"enable_message_signing,omitempty"`
	EnableStrictSignatureVerification bool                   `protobuf:"varint,8,opt,name=enable_strict_signature_verification,json=enableStrictSignatureVerification,proto3" json:"enable_strict_signature_verification,omitempty"`
	MessageIdCacheSize                int32                  `protobuf:"varint,9,opt,name=message_id_cache_size,json=messageIdCacheSize,proto3" json:"message_id_cache_size,omitempty"`
	MessageTtl                        *durationpb.Duration   `protobuf:"bytes,10,opt,name=message_ttl,json=messageTtl,proto3" json:"message_ttl,omitempty"`
	MaxMessageSize                    int32                  `protobuf:"varint,11,opt,name=max_message_size,json=maxMessageSize,proto3" json:"max_message_size,omitempty"`
	// Intent monitoring configuration
	IntentMonitoring *IntentMonitoring `protobuf:"bytes,20,opt,name=intent_monitoring,json=intentMonitoring,proto3" json:"intent_monitoring,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Transport) GetEnableGossipsub() bool {
	if x != nil {
		return x.EnableGossipsub
	}
	return false
}

func (x *Transport) GetGossipsubHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.GossipsubHeartbeatInterval
	}
	return nil
}

func (x *Transport) GetGossipsubD() int32 {
	if x != nil {
		return x.GossipsubD
	}
	return 0
}

func (x *Transport) GetGossipsubDLo() int32 {
	if x != nil {
		return x.GossipsubDLo
	}
	return 0
}

func (x *Transport) GetGossipsubDHi() int32 {
	if x != nil {
		return x.GossipsubDHi
	}
	return 0
}

func (x *Transport) GetGossipsubFanoutTtl() *durationpb.Duration {
	if x != nil {
		return x.GossipsubFanoutTtl
	}
	return nil
}

func (x *Transport) GetEnableMessageSigning() bool {
	if x != nil {
		return x.EnableMessageSigning
	}
	return false
}

func (x *Transport) GetEnableStrictSignatureVerification() bool {
	if x != nil {
		return x.EnableStrictSignatureVerification
	}
	return false
}

func (x *Transport) GetMessageIdCacheSize() int32 {
	if x != nil {
		return x.MessageIdCacheSize
	}
	return 0
}

func (x *Transport) GetMessageTtl() *durationpb.Duration {
	if x != nil {
		return x.MessageTtl
	}
	return nil
}

func (x *Transport) GetMaxMessageSize() int32 {
	if x != nil {
		return x.MaxMessageSize
	}
	return 0
}

func (x *Transport) GetIntentMonitoring() *IntentMonitoring {
	if x != nil {
		return x.IntentMonitoring
	}
	return nil
}

// Intent monitoring configuration
type IntentMonitoring struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscription mode: "wildcard", "explicit", "all", "disabled"
	// Default is "all" - listen to all topics
	SubscriptionMode string `protobuf:"bytes,1,opt,name=subscription_mode,json=subscriptionMode,proto3" json:"subscription_mode,omitempty"`
	// Explicit topic list (used in explicit mode)
	ExplicitTopics []string `protobuf:"bytes,2,rep,name=explicit_topics,json=explicitTopics,proto3" json:"explicit_topics,omitempty"`
	// Wildcard pattern list for topic matching
	WildcardPatterns []string `protobuf:"bytes,3,rep,name=wildcard_patterns,json=wildcardPatterns,proto3" json:"wildcard_patterns,omitempty"`
	// Intent filter configuration
	Filter *IntentFilter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Statistics configuration
	Statistics *StatisticsConfig `protobuf:"bytes,5,opt,name=statistics,proto3" json:"statistics,omitempty"`
	// Performance configuration
	Performance   *PerformanceConfig `protobuf:"bytes,6,opt,name=performance,proto3" json:"performance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentMonitoring) Reset() {
	*x = IntentMonitoring{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentMonitoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentMonitoring) ProtoMessage() {}

func (x *IntentMonitoring) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentMonitoring.ProtoReflect.Descriptor instead.
func (*IntentMonitoring) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *IntentMonitoring) GetSubscriptionMode() string {
	if x != nil {
		return x.SubscriptionMode
	}
	return ""
}

func (x *IntentMonitoring) GetExplicitTopics() []string {
	if x != nil {
		return x.ExplicitTopics
	}
	return nil
}

func (x *IntentMonitoring) GetWildcardPatterns() []string {
	if x != nil {
		return x.WildcardPatterns
	}
	return nil
}

func (x *IntentMonitoring) GetFilter() *IntentFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *IntentMonitoring) GetStatistics() *StatisticsConfig {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *IntentMonitoring) GetPerformance() *PerformanceConfig {
	if x != nil {
		return x.Performance
	}
	return nil
}

// Intent filter configuration
type IntentFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed intent types (empty means allow all)
	AllowedTypes []string `protobuf:"bytes,1,rep,name=allowed_types,json=allowedTypes,proto3" json:"allowed_types,omitempty"`
	// Blocked intent types
	BlockedTypes []string `protobuf:"bytes,2,rep,name=blocked_types,json=blockedTypes,proto3" json:"blocked_types,omitempty"`
	// Sender filter rules
	AllowedSenders []string `protobuf:"bytes,3,rep,name=allowed_senders,json=allowedSenders,proto3" json:"allowed_senders,omitempty"`
	BlockedSenders []string `protobuf:"bytes,4,rep,name=blocked_senders,json=blockedSenders,proto3" json:"blocked_senders,omitempty"`
	// Priority filter
	MinPriority   int32 `protobuf:"varint,5,opt,name=min_priority,json=minPriority,proto3" json:"min_priority,omitempty"`
	MaxPriority   int32 `protobuf:"varint,6,opt,name=max_priority,json=maxPriority,proto3" json:"max_priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentFilter) Reset() {
	*x = IntentFilter{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentFilter) ProtoMessage() {}

func (x *IntentFilter) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentFilter.ProtoReflect.Descriptor instead.
func (*IntentFilter) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *IntentFilter) GetAllowedTypes() []string {
	if x != nil {
		return x.AllowedTypes
	}
	return nil
}

func (x *IntentFilter) GetBlockedTypes() []string {
	if x != nil {
		return x.BlockedTypes
	}
	return nil
}

func (x *IntentFilter) GetAllowedSenders() []string {
	if x != nil {
		return x.AllowedSenders
	}
	return nil
}

func (x *IntentFilter) GetBlockedSenders() []string {
	if x != nil {
		return x.BlockedSenders
	}
	return nil
}

func (x *IntentFilter) GetMinPriority() int32 {
	if x != nil {
		return x.MinPriority
	}
	return 0
}

func (x *IntentFilter) GetMaxPriority() int32 {
	if x != nil {
		return x.MaxPriority
	}
	return 0
}

// Statistics configuration
type StatisticsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable statistics collection
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Statistics data retention period
	RetentionPeriod *durationpb.Duration `protobuf:"bytes,2,opt,name=retention_period,json=retentionPeriod,proto3" json:"retention_period,omitempty"`
	// Statistics aggregation interval
	AggregationInterval *durationpb.Duration `protobuf:"bytes,3,opt,name=aggregation_interval,json=aggregationInterval,proto3" json:"aggregation_interval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatisticsConfig) Reset() {
	*x = StatisticsConfig{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsConfig) ProtoMessage() {}

func (x *StatisticsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsConfig.ProtoReflect.Descriptor instead.
func (*StatisticsConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *StatisticsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatisticsConfig) GetRetentionPeriod() *durationpb.Duration {
	if x != nil {
		return x.RetentionPeriod
	}
	return nil
}

func (x *StatisticsConfig) GetAggregationInterval() *durationpb.Duration {
	if x != nil {
		return x.AggregationInterval
	}
	return nil
}

// Performance configuration
type PerformanceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum concurrent subscriptions
	MaxSubscriptions int32 `protobuf:"varint,1,opt,name=max_subscriptions,json=maxSubscriptions,proto3" json:"max_subscriptions,omitempty"`
	// Message processing buffer size
	MessageBufferSize int32 `protobuf:"varint,2,opt,name=message_buffer_size,json=messageBufferSize,proto3" json:"message_buffer_size,omitempty"`
	// Batch processing size
	BatchSize     int32 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceConfig) Reset() {
	*x = PerformanceConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceConfig) ProtoMessage() {}

func (x *PerformanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceConfig.ProtoReflect.Descriptor instead.
func (*PerformanceConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *PerformanceConfig) GetMaxSubscriptions() int32 {
	if x != nil {
		return x.MaxSubscriptions
	}
	return 0
}

func (x *PerformanceConfig) GetMessageBufferSize() int32 {
	if x != nil {
		return x.MessageBufferSize
	}
	return 0
}

func (x *PerformanceConfig) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xb5\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12!\n" +
	"\x03p2p\x18\x03 \x01(\v2\x0f.kratos.api.P2PR\x03p2p\x123\n" +
	"\ttransport\x18\x04 \x01(\v2\x15.kratos.api.TransportR\ttransport\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xdd\x02\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"\xa5\x02\n" +
	"\x03P2P\x12)\n" +
	"\x10listen_addresses\x18\x01 \x03(\tR\x0flistenAddresses\x12'\n" +
	"\x0fbootstrap_peers\x18\x02 \x03(\tR\x0ebootstrapPeers\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x12\x1f\n" +
	"\venable_mdns\x18\x04 \x01(\bR\n" +
	"enableMdns\x12\x1d\n" +
	"\n" +
	"enable_dht\x18\x05 \x01(\bR\tenableDht\x12\x19\n" +
	"\bdata_dir\x18\x06 \x01(\tR\adataDir\x12'\n" +
	"\x0fmax_connections\x18\a \x01(\x05R\x0emaxConnections\x12%\n" +
	"\x0eenable_signing\x18\b \x01(\bR\renableSigning\"\xb8\x05\n" +
	"\tTransport\x12)\n" +
	"\x10enable_gossipsub\x18\x01 \x01(\bR\x0fenableGossipsub\x12[\n" +
	"\x1cgossipsub_heartbeat_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x1agossipsubHeartbeatInterval\x12\x1f\n" +
	"\vgossipsub_d\x18\x03 \x01(\x05R\n" +
	"gossipsubD\x12$\n" +
	"\x0egossipsub_d_lo\x18\x04 \x01(\x05R\fgossipsubDLo\x12$\n" +
	"\x0egossipsub_d_hi\x18\x05 \x01(\x05R\fgossipsubDHi\x12K\n" +
	"\x14gossipsub_fanout_ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x12gossipsubFanoutTtl\x124\n" +
	"\x16enable_message_signing\x18\a \x01(\bR\x14enableMessageSigning\x12O\n" +
	"$enable_strict_signature_verification\x18\b \x01(\bR!enableStrictSignatureVerification\x121\n" +
	"\x15message_id_cache_size\x18\t \x01(\x05R\x12messageIdCacheSize\x12:\n" +
	"\vmessage_ttl\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\n" +
	"messageTtl\x12(\n" +
	"\x10max_message_size\x18\v \x01(\x05R\x0emaxMessageSize\x12I\n" +
	"\x11intent_monitoring\x18\x14 \x01(\v2\x1c.kratos.api.IntentMonitoringR\x10intentMonitoring\"\xc6\x02\n" +
	"\x10IntentMonitoring\x12+\n" +
	"\x11subscription_mode\x18\x01 \x01(\tR\x10subscriptionMode\x12'\n" +
	"\x0fexplicit_topics\x18\x02 \x03(\tR\x0eexplicitTopics\x12+\n" +
	"\x11wildcard_patterns\x18\x03 \x03(\tR\x10wildcardPatterns\x120\n" +
	"\x06filter\x18\x04 \x01(\v2\x18.kratos.api.IntentFilterR\x06filter\x12<\n" +
	"\n" +
	"statistics\x18\x05 \x01(\v2\x1c.kratos.api.StatisticsConfigR\n" +
	"statistics\x12?\n" +
	"\vperformance\x18\x06 \x01(\v2\x1d.kratos.api.PerformanceConfigR\vperformance\"\xf0\x01\n" +
	"\fIntentFilter\x12#\n" +
	"\rallowed_types\x18\x01 \x03(\tR\fallowedTypes\x12#\n" +
	"\rblocked_types\x18\x02 \x03(\tR\fblockedTypes\x12'\n" +
	"\x0fallowed_senders\x18\x03 \x03(\tR\x0eallowedSenders\x12'\n" +
	"\x0fblocked_senders\x18\x04 \x03(\tR\x0eblockedSenders\x12!\n" +
	"\fmin_priority\x18\x05 \x01(\x05R\vminPriority\x12!\n" +
	"\fmax_priority\x18\x06 \x01(\x05R\vmaxPriority\"\xc0\x01\n" +
	"\x10StatisticsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x10retention_period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fretentionPeriod\x12L\n" +
	"\x14aggregation_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x13aggregationInterval\"\x8f\x01\n" +
	"\x11PerformanceConfig\x12+\n" +
	"\x11max_subscriptions\x18\x01 \x01(\x05R\x10maxSubscriptions\x12.\n" +
	"\x13message_buffer_size\x18\x02 \x01(\x05R\x11messageBufferSize\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSizeB1Z/pin_intent_broadcast_network/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*P2P)(nil),                 // 3: kratos.api.P2P
	(*Transport)(nil),           // 4: kratos.api.Transport
	(*IntentMonitoring)(nil),    // 5: kratos.api.IntentMonitoring
	(*IntentFilter)(nil),        // 6: kratos.api.IntentFilter
	(*StatisticsConfig)(nil),    // 7: kratos.api.StatisticsConfig
	(*PerformanceConfig)(nil),   // 8: kratos.api.PerformanceConfig
	(*Server_HTTP)(nil),         // 9: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 10: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 11: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 12: kratos.api.Data.Redis
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.p2p:type_name -> kratos.api.P2P
	4,  // 3: kratos.api.Bootstrap.transport:type_name -> kratos.api.Transport
	9,  // 4: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	10, // 5: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	11, // 6: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	12, // 7: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	13, // 8: kratos.api.Transport.gossipsub_heartbeat_interval:type_name -> google.protobuf.Duration
	13, // 9: kratos.api.Transport.gossipsub_fanout_ttl:type_name -> google.protobuf.Duration
	13, // 10: kratos.api.Transport.message_ttl:type_name -> google.protobuf.Duration
	5,  // 11: kratos.api.Transport.intent_monitoring:type_name -> kratos.api.IntentMonitoring
	6,  // 12: kratos.api.IntentMonitoring.filter:type_name -> kratos.api.IntentFilter
	7,  // 13: kratos.api.IntentMonitoring.statistics:type_name -> kratos.api.StatisticsConfig
	8,  // 14: kratos.api.IntentMonitoring.performance:type_name -> kratos.api.PerformanceConfig
	13, // 15: kratos.api.StatisticsConfig.retention_period:type_name -> google.protobuf.Duration
	13, // 16: kratos.api.StatisticsConfig.aggregation_interval:type_name -> google.protobuf.Duration
	13, // 17: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 18: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 19: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	13, // 20: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
