// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pinai_intent/v1/intent.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Intent status enumeration
type IntentStatus int32

const (
	IntentStatus_INTENT_STATUS_UNSPECIFIED IntentStatus = 0
	IntentStatus_INTENT_STATUS_CREATED     IntentStatus = 1
	IntentStatus_INTENT_STATUS_VALIDATED   IntentStatus = 2
	IntentStatus_INTENT_STATUS_BROADCASTED IntentStatus = 3
	IntentStatus_INTENT_STATUS_PROCESSED   IntentStatus = 4
	IntentStatus_INTENT_STATUS_MATCHED     IntentStatus = 5
	IntentStatus_INTENT_STATUS_COMPLETED   IntentStatus = 6
	IntentStatus_INTENT_STATUS_FAILED      IntentStatus = 7
	IntentStatus_INTENT_STATUS_EXPIRED     IntentStatus = 8
)

// Enum value maps for IntentStatus.
var (
	IntentStatus_name = map[int32]string{
		0: "INTENT_STATUS_UNSPECIFIED",
		1: "INTENT_STATUS_CREATED",
		2: "INTENT_STATUS_VALIDATED",
		3: "INTENT_STATUS_BROADCASTED",
		4: "INTENT_STATUS_PROCESSED",
		5: "INTENT_STATUS_MATCHED",
		6: "INTENT_STATUS_COMPLETED",
		7: "INTENT_STATUS_FAILED",
		8: "INTENT_STATUS_EXPIRED",
	}
	IntentStatus_value = map[string]int32{
		"INTENT_STATUS_UNSPECIFIED": 0,
		"INTENT_STATUS_CREATED":     1,
		"INTENT_STATUS_VALIDATED":   2,
		"INTENT_STATUS_BROADCASTED": 3,
		"INTENT_STATUS_PROCESSED":   4,
		"INTENT_STATUS_MATCHED":     5,
		"INTENT_STATUS_COMPLETED":   6,
		"INTENT_STATUS_FAILED":      7,
		"INTENT_STATUS_EXPIRED":     8,
	}
)

func (x IntentStatus) Enum() *IntentStatus {
	p := new(IntentStatus)
	*p = x
	return p
}

func (x IntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pinai_intent_v1_intent_proto_enumTypes[0].Descriptor()
}

func (IntentStatus) Type() protoreflect.EnumType {
	return &file_pinai_intent_v1_intent_proto_enumTypes[0]
}

func (x IntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentStatus.Descriptor instead.
func (IntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{0}
}

// Tag represents a data access requirement with fee and tradability information
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`           // Name of the data tag (e.g., "shopping_history")
	TagFee        string                 `protobuf:"bytes,2,opt,name=tag_fee,json=tagFee,proto3" json:"tag_fee,omitempty"`              // Access fee in Octa (Aptos native token smallest unit)
	IsTradable    bool                   `protobuf:"varint,3,opt,name=is_tradable,json=isTradable,proto3" json:"is_tradable,omitempty"` // Whether this tag can be requested by agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *Tag) GetTagFee() string {
	if x != nil {
		return x.TagFee
	}
	return ""
}

func (x *Tag) GetIsTradable() bool {
	if x != nil {
		return x.IsTradable
	}
	return false
}

// IntentManifest describes the intent task and requirements
type IntentManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`                                                                                           // Human readable task description
	Requirements  map[string]string      `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional task requirements
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                                                                                     // Optional context information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentManifest) Reset() {
	*x = IntentManifest{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentManifest) ProtoMessage() {}

func (x *IntentManifest) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentManifest.ProtoReflect.Descriptor instead.
func (*IntentManifest) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{1}
}

func (x *IntentManifest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *IntentManifest) GetRequirements() map[string]string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *IntentManifest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// Intent message structure
type Intent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload            []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp          int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId           string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Signature          []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureAlgorithm string                 `protobuf:"bytes,7,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status             IntentStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=api.pinai_intent.v1.IntentStatus" json:"status,omitempty"`
	Priority           int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Ttl                int64                  `protobuf:"varint,11,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ProcessedAt        int64                  `protobuf:"varint,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	Error              string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	UserAddress        string                 `protobuf:"bytes,14,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`          // User's Aptos address
	IntentManifest     *IntentManifest        `protobuf:"bytes,15,opt,name=intent_manifest,json=intentManifest,proto3" json:"intent_manifest,omitempty"` // Intent description and requirements
	RelevantTags       []*Tag                 `protobuf:"bytes,16,rep,name=relevant_tags,json=relevantTags,proto3" json:"relevant_tags,omitempty"`       // List of required data tags
	MaxDuration        int64                  `protobuf:"varint,17,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`         // Intent validity duration in seconds
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{2}
}

func (x *Intent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Intent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Intent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Intent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Intent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Intent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Intent) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *Intent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Intent) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *Intent) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Intent) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Intent) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

func (x *Intent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Intent) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *Intent) GetIntentManifest() *IntentManifest {
	if x != nil {
		return x.IntentManifest
	}
	return nil
}

func (x *Intent) GetRelevantTags() []*Tag {
	if x != nil {
		return x.RelevantTags
	}
	return nil
}

func (x *Intent) GetMaxDuration() int64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

// CreateIntent request message
type CreateIntentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority       int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Ttl            int64                  `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	UserAddress    string                 `protobuf:"bytes,7,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`          // User's Aptos address
	IntentManifest *IntentManifest        `protobuf:"bytes,8,opt,name=intent_manifest,json=intentManifest,proto3" json:"intent_manifest,omitempty"` // Intent description and requirements
	RelevantTags   []*Tag                 `protobuf:"bytes,9,rep,name=relevant_tags,json=relevantTags,proto3" json:"relevant_tags,omitempty"`       // List of required data tags
	MaxDuration    int64                  `protobuf:"varint,10,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`        // Intent validity duration in seconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateIntentRequest) Reset() {
	*x = CreateIntentRequest{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentRequest) ProtoMessage() {}

func (x *CreateIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateIntentRequest) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIntentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIntentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateIntentRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *CreateIntentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateIntentRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateIntentRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CreateIntentRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *CreateIntentRequest) GetIntentManifest() *IntentManifest {
	if x != nil {
		return x.IntentManifest
	}
	return nil
}

func (x *CreateIntentRequest) GetRelevantTags() []*Tag {
	if x != nil {
		return x.RelevantTags
	}
	return nil
}

func (x *CreateIntentRequest) GetMaxDuration() int64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

// CreateIntent response message
type CreateIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentResponse) Reset() {
	*x = CreateIntentResponse{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentResponse) ProtoMessage() {}

func (x *CreateIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateIntentResponse) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateIntentResponse) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *CreateIntentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateIntentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BroadcastIntent request message
type BroadcastIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastIntentRequest) Reset() {
	*x = BroadcastIntentRequest{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastIntentRequest) ProtoMessage() {}

func (x *BroadcastIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastIntentRequest.ProtoReflect.Descriptor instead.
func (*BroadcastIntentRequest) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastIntentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *BroadcastIntentRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// BroadcastIntent response message
type BroadcastIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IntentId      string                 `protobuf:"bytes,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastIntentResponse) Reset() {
	*x = BroadcastIntentResponse{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastIntentResponse) ProtoMessage() {}

func (x *BroadcastIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastIntentResponse.ProtoReflect.Descriptor instead.
func (*BroadcastIntentResponse) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastIntentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *BroadcastIntentResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BroadcastIntentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// QueryIntents request message
type QueryIntentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        IntentStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=api.pinai_intent.v1.IntentStatus" json:"status,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIntentsRequest) Reset() {
	*x = QueryIntentsRequest{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIntentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIntentsRequest) ProtoMessage() {}

func (x *QueryIntentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIntentsRequest.ProtoReflect.Descriptor instead.
func (*QueryIntentsRequest) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{7}
}

func (x *QueryIntentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryIntentsRequest) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *QueryIntentsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryIntentsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryIntentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryIntentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// QueryIntents response message
type QueryIntentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intents       []*Intent              `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIntentsResponse) Reset() {
	*x = QueryIntentsResponse{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIntentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIntentsResponse) ProtoMessage() {}

func (x *QueryIntentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIntentsResponse.ProtoReflect.Descriptor instead.
func (*QueryIntentsResponse) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{8}
}

func (x *QueryIntentsResponse) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *QueryIntentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetIntentStatus request message
type GetIntentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentStatusRequest) Reset() {
	*x = GetIntentStatusRequest{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentStatusRequest) ProtoMessage() {}

func (x *GetIntentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIntentStatusRequest) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{9}
}

func (x *GetIntentStatusRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

// GetIntentStatus response message
type GetIntentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentStatusResponse) Reset() {
	*x = GetIntentStatusResponse{}
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentStatusResponse) ProtoMessage() {}

func (x *GetIntentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinai_intent_v1_intent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetIntentStatusResponse) Descriptor() ([]byte, []int) {
	return file_pinai_intent_v1_intent_proto_rawDescGZIP(), []int{10}
}

func (x *GetIntentStatusResponse) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

var File_pinai_intent_v1_intent_proto protoreflect.FileDescriptor

const file_pinai_intent_v1_intent_proto_rawDesc = "" +
	"\n" +
	"\x1cpinai_intent/v1/intent.proto\x12\x13api.pinai_intent.v1\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\x03Tag\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12\x17\n" +
	"\atag_fee\x18\x02 \x01(\tR\x06tagFee\x12\x1f\n" +
	"\vis_tradable\x18\x03 \x01(\bR\n" +
	"isTradable\"\xda\x01\n" +
	"\x0eIntentManifest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12Y\n" +
	"\frequirements\x18\x02 \x03(\v25.api.pinai_intent.v1.IntentManifest.RequirementsEntryR\frequirements\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x1a?\n" +
	"\x11RequirementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x05\n" +
	"\x06Intent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12/\n" +
	"\x13signature_algorithm\x18\a \x01(\tR\x12signatureAlgorithm\x12E\n" +
	"\bmetadata\x18\b \x03(\v2).api.pinai_intent.v1.Intent.MetadataEntryR\bmetadata\x129\n" +
	"\x06status\x18\t \x01(\x0e2!.api.pinai_intent.v1.IntentStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12\x10\n" +
	"\x03ttl\x18\v \x01(\x03R\x03ttl\x12!\n" +
	"\fprocessed_at\x18\f \x01(\x03R\vprocessedAt\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x12!\n" +
	"\fuser_address\x18\x0e \x01(\tR\vuserAddress\x12L\n" +
	"\x0fintent_manifest\x18\x0f \x01(\v2#.api.pinai_intent.v1.IntentManifestR\x0eintentManifest\x12=\n" +
	"\rrelevant_tags\x18\x10 \x03(\v2\x18.api.pinai_intent.v1.TagR\frelevantTags\x12!\n" +
	"\fmax_duration\x18\x11 \x01(\x03R\vmaxDuration\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x03\n" +
	"\x13CreateIntentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.api.pinai_intent.v1.CreateIntentRequest.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\x12!\n" +
	"\fuser_address\x18\a \x01(\tR\vuserAddress\x12L\n" +
	"\x0fintent_manifest\x18\b \x01(\v2#.api.pinai_intent.v1.IntentManifestR\x0eintentManifest\x12=\n" +
	"\rrelevant_tags\x18\t \x03(\v2\x18.api.pinai_intent.v1.TagR\frelevantTags\x12!\n" +
	"\fmax_duration\x18\n" +
	" \x01(\x03R\vmaxDuration\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x14CreateIntentResponse\x123\n" +
	"\x06intent\x18\x01 \x01(\v2\x1b.api.pinai_intent.v1.IntentR\x06intent\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"K\n" +
	"\x16BroadcastIntentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x80\x01\n" +
	"\x17BroadcastIntentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\tR\bintentId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xcc\x01\n" +
	"\x13QueryIntentsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.api.pinai_intent.v1.IntentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"c\n" +
	"\x14QueryIntentsResponse\x125\n" +
	"\aintents\x18\x01 \x03(\v2\x1b.api.pinai_intent.v1.IntentR\aintents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"5\n" +
	"\x16GetIntentStatusRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\"N\n" +
	"\x17GetIntentStatusResponse\x123\n" +
	"\x06intent\x18\x01 \x01(\v2\x1b.api.pinai_intent.v1.IntentR\x06intent*\x8e\x02\n" +
	"\fIntentStatus\x12\x1d\n" +
	"\x19INTENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INTENT_STATUS_CREATED\x10\x01\x12\x1b\n" +
	"\x17INTENT_STATUS_VALIDATED\x10\x02\x12\x1d\n" +
	"\x19INTENT_STATUS_BROADCASTED\x10\x03\x12\x1b\n" +
	"\x17INTENT_STATUS_PROCESSED\x10\x04\x12\x19\n" +
	"\x15INTENT_STATUS_MATCHED\x10\x05\x12\x1b\n" +
	"\x17INTENT_STATUS_COMPLETED\x10\x06\x12\x18\n" +
	"\x14INTENT_STATUS_FAILED\x10\a\x12\x19\n" +
	"\x15INTENT_STATUS_EXPIRED\x10\b2\xd4\x04\n" +
	"\rIntentService\x12\x8b\x01\n" +
	"\fCreateIntent\x12(.api.pinai_intent.v1.CreateIntentRequest\x1a).api.pinai_intent.v1.CreateIntentResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/pinai_intent/intent/create\x12\x97\x01\n" +
	"\x0fBroadcastIntent\x12+.api.pinai_intent.v1.BroadcastIntentRequest\x1a,.api.pinai_intent.v1.BroadcastIntentResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/pinai_intent/intent/broadcast\x12\x86\x01\n" +
	"\fQueryIntents\x12(.api.pinai_intent.v1.QueryIntentsRequest\x1a).api.pinai_intent.v1.QueryIntentsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/pinai_intent/intent/list\x12\x91\x01\n" +
	"\x0fGetIntentStatus\x12+.api.pinai_intent.v1.GetIntentStatusRequest\x1a,.api.pinai_intent.v1.GetIntentStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/pinai_intent/intent/statusBLZJgithub.com/pin-project/pin_intent_broadcast_network/api/pinai_intent/v1;v1b\x06proto3"

var (
	file_pinai_intent_v1_intent_proto_rawDescOnce sync.Once
	file_pinai_intent_v1_intent_proto_rawDescData []byte
)

func file_pinai_intent_v1_intent_proto_rawDescGZIP() []byte {
	file_pinai_intent_v1_intent_proto_rawDescOnce.Do(func() {
		file_pinai_intent_v1_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pinai_intent_v1_intent_proto_rawDesc), len(file_pinai_intent_v1_intent_proto_rawDesc)))
	})
	return file_pinai_intent_v1_intent_proto_rawDescData
}

var file_pinai_intent_v1_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pinai_intent_v1_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pinai_intent_v1_intent_proto_goTypes = []any{
	(IntentStatus)(0),               // 0: api.pinai_intent.v1.IntentStatus
	(*Tag)(nil),                     // 1: api.pinai_intent.v1.Tag
	(*IntentManifest)(nil),          // 2: api.pinai_intent.v1.IntentManifest
	(*Intent)(nil),                  // 3: api.pinai_intent.v1.Intent
	(*CreateIntentRequest)(nil),     // 4: api.pinai_intent.v1.CreateIntentRequest
	(*CreateIntentResponse)(nil),    // 5: api.pinai_intent.v1.CreateIntentResponse
	(*BroadcastIntentRequest)(nil),  // 6: api.pinai_intent.v1.BroadcastIntentRequest
	(*BroadcastIntentResponse)(nil), // 7: api.pinai_intent.v1.BroadcastIntentResponse
	(*QueryIntentsRequest)(nil),     // 8: api.pinai_intent.v1.QueryIntentsRequest
	(*QueryIntentsResponse)(nil),    // 9: api.pinai_intent.v1.QueryIntentsResponse
	(*GetIntentStatusRequest)(nil),  // 10: api.pinai_intent.v1.GetIntentStatusRequest
	(*GetIntentStatusResponse)(nil), // 11: api.pinai_intent.v1.GetIntentStatusResponse
	nil,                             // 12: api.pinai_intent.v1.IntentManifest.RequirementsEntry
	nil,                             // 13: api.pinai_intent.v1.Intent.MetadataEntry
	nil,                             // 14: api.pinai_intent.v1.CreateIntentRequest.MetadataEntry
}
var file_pinai_intent_v1_intent_proto_depIdxs = []int32{
	12, // 0: api.pinai_intent.v1.IntentManifest.requirements:type_name -> api.pinai_intent.v1.IntentManifest.RequirementsEntry
	13, // 1: api.pinai_intent.v1.Intent.metadata:type_name -> api.pinai_intent.v1.Intent.MetadataEntry
	0,  // 2: api.pinai_intent.v1.Intent.status:type_name -> api.pinai_intent.v1.IntentStatus
	2,  // 3: api.pinai_intent.v1.Intent.intent_manifest:type_name -> api.pinai_intent.v1.IntentManifest
	1,  // 4: api.pinai_intent.v1.Intent.relevant_tags:type_name -> api.pinai_intent.v1.Tag
	14, // 5: api.pinai_intent.v1.CreateIntentRequest.metadata:type_name -> api.pinai_intent.v1.CreateIntentRequest.MetadataEntry
	2,  // 6: api.pinai_intent.v1.CreateIntentRequest.intent_manifest:type_name -> api.pinai_intent.v1.IntentManifest
	1,  // 7: api.pinai_intent.v1.CreateIntentRequest.relevant_tags:type_name -> api.pinai_intent.v1.Tag
	3,  // 8: api.pinai_intent.v1.CreateIntentResponse.intent:type_name -> api.pinai_intent.v1.Intent
	0,  // 9: api.pinai_intent.v1.QueryIntentsRequest.status:type_name -> api.pinai_intent.v1.IntentStatus
	3,  // 10: api.pinai_intent.v1.QueryIntentsResponse.intents:type_name -> api.pinai_intent.v1.Intent
	3,  // 11: api.pinai_intent.v1.GetIntentStatusResponse.intent:type_name -> api.pinai_intent.v1.Intent
	4,  // 12: api.pinai_intent.v1.IntentService.CreateIntent:input_type -> api.pinai_intent.v1.CreateIntentRequest
	6,  // 13: api.pinai_intent.v1.IntentService.BroadcastIntent:input_type -> api.pinai_intent.v1.BroadcastIntentRequest
	8,  // 14: api.pinai_intent.v1.IntentService.QueryIntents:input_type -> api.pinai_intent.v1.QueryIntentsRequest
	10, // 15: api.pinai_intent.v1.IntentService.GetIntentStatus:input_type -> api.pinai_intent.v1.GetIntentStatusRequest
	5,  // 16: api.pinai_intent.v1.IntentService.CreateIntent:output_type -> api.pinai_intent.v1.CreateIntentResponse
	7,  // 17: api.pinai_intent.v1.IntentService.BroadcastIntent:output_type -> api.pinai_intent.v1.BroadcastIntentResponse
	9,  // 18: api.pinai_intent.v1.IntentService.QueryIntents:output_type -> api.pinai_intent.v1.QueryIntentsResponse
	11, // 19: api.pinai_intent.v1.IntentService.GetIntentStatus:output_type -> api.pinai_intent.v1.GetIntentStatusResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pinai_intent_v1_intent_proto_init() }
func file_pinai_intent_v1_intent_proto_init() {
	if File_pinai_intent_v1_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pinai_intent_v1_intent_proto_rawDesc), len(file_pinai_intent_v1_intent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinai_intent_v1_intent_proto_goTypes,
		DependencyIndexes: file_pinai_intent_v1_intent_proto_depIdxs,
		EnumInfos:         file_pinai_intent_v1_intent_proto_enumTypes,
		MessageInfos:      file_pinai_intent_v1_intent_proto_msgTypes,
	}.Build()
	File_pinai_intent_v1_intent_proto = out.File
	file_pinai_intent_v1_intent_proto_goTypes = nil
	file_pinai_intent_v1_intent_proto_depIdxs = nil
}
