server:
  http:
    addr: 0.0.0.0:8102
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9102
    timeout: 1s

data:
  database:
    driver: memory
    source: ""
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 2
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s

p2p:
  listen_addresses:
    - /ip4/0.0.0.0/tcp/9202
  protocol_id: "/pin-automation/1.0.0"
  enable_mdns: true
  enable_dht: true
  data_dir: "./test_data/automation/node3/p2p"
  max_connections: 20
  enable_signing: true

transport:
  enable_gossipsub: true
  gossipsub_heartbeat_interval: 1s
  gossipsub_d: 6
  gossipsub_d_lo: 4
  gossipsub_d_hi: 12
  gossipsub_fanout_ttl: 60s
  enable_message_signing: true
  enable_strict_signature_verification: true
  message_id_cache_size: 1000
  message_ttl: 300s
  max_message_size: 1048576
  
  # Intent monitoring configuration
  intent_monitoring:
    subscription_mode: "all"
    wildcard_patterns:
      - "automation-test.*"
    explicit_topics:
      - "automation-test.intent-broadcast"
      - "automation-test.bidding"
      - "automation-test.matching"
    filter:
      allowed_types: ["data_access", "computation"]
      blocked_types: []
      allowed_senders: []
      blocked_senders: []
      min_priority: 0
      max_priority: 10
    statistics:
      enabled: true
      retention_period: "3600s"
      aggregation_interval: "60s"
    performance:
      max_subscriptions: 100
      message_buffer_size: 1000
      batch_size: 10
