server:
  http:
    addr: 0.0.0.0:8011
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9011
    timeout: 1s

data:
  database:
    driver: sqlite
    source: "test_data/node2/data.db"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

p2p:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/9012"
  bootstrap_peers: []
  protocol_id: "/intent-broadcast/1.0.0"
  enable_mdns: true
  enable_dht: true
  data_dir: "test_data/node2/p2p"
  max_connections: 50
  enable_signing: true

transport:
  enable_gossipsub: true
  gossipsub_heartbeat_interval: 1s
  gossipsub_d: 6
  gossipsub_d_lo: 4
  gossipsub_d_hi: 12
  gossipsub_fanout_ttl: 60s
  enable_message_signing: true
  enable_strict_signature_verification: true
  message_id_cache_size: 1000
  message_ttl: 300s
  max_message_size: 1048576

  # Intent monitoring configuration
  intent_monitoring:
    # Subscription mode: "wildcard" | "explicit" | "all" | "disabled"
    # Default is "all" - listen to all intent broadcast topics
    subscription_mode: "all"

    # Wildcard patterns for topic matching (used in wildcard mode)
    wildcard_patterns:
      - "intent-broadcast.*"
      - "intent-matching.*"

    # Explicit topic list (used in explicit mode)
    explicit_topics:
      - "intent-broadcast.trade"
      - "intent-broadcast.swap"
      - "intent-broadcast.exchange"
      - "intent-broadcast.transfer"
      - "intent-broadcast.send"
      - "intent-broadcast.payment"
      - "intent-broadcast.lending"
      - "intent-broadcast.borrow"
      - "intent-broadcast.loan"
      - "intent-broadcast.investment"
      - "intent-broadcast.staking"
      - "intent-broadcast.yield"
      - "intent-broadcast.general"

    # Intent filter configuration
    filter:
      allowed_types: [] # Empty means allow all types
      blocked_types: []
      allowed_senders: []
      blocked_senders: []
      min_priority: 0
      max_priority: 10

    # Statistics configuration
    statistics:
      enabled: true
      retention_period: "86400s"
      aggregation_interval: "60s"

    # Performance configuration
    performance:
      max_subscriptions: 100
      message_buffer_size: 1000
      batch_size: 10
