server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: sqlite
    source: "test_data/node1/data.db"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

p2p:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/9001"
  bootstrap_peers: []
  protocol_id: "/intent-broadcast/1.0.0"
  enable_mdns: true
  enable_dht: true
  data_dir: "test_data/node1/p2p"
  max_connections: 50
  enable_signing: true

transport:
  enable_gossipsub: true
  gossipsub_heartbeat_interval: 1s
  gossipsub_d: 6
  gossipsub_d_lo: 4
  gossipsub_d_hi: 12
  gossipsub_fanout_ttl: 60s
  enable_message_signing: true
  enable_strict_signature_verification: true
  message_id_cache_size: 1000
  message_ttl: 300s
  max_message_size: 1048576
